bot_token: 
bot_prefix: /
command_title: Commands
commands:
  - /+say channelName [message to send to channel]
  - /-say
  - /delete
  - /jokeHere
  - /jokeThere MentionChannel
  - /factsHere
  - /factsThere MentionChannel
  - /help
