# User bot token
token: ""
# You can create your own facts and jokes by creating a yml file with a "quotes" property with
# a list of strings and then providing a path to that file here.
facts: 'default'
jokes: 'default'
# A list of role IDs
whitelist: []