bot_token:
bot_prefix: /
command_title: Commands
commands:
  - /set channelName message to send to channel
  - /jokeHere
  - /jokeThere channelName
  - /factsHere
  - /factsThere channelName
  - /help DikDik

